### ISSUE TITLE
[Bug]: Crashes to launcher without opening minecraft window

### ISSUE THREAD

**Issue by Baggytrousers27** [Cheos137/ArmorpointsPlusplus#16]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Forge 38.0.14
ArmorPoints++ v2.1.3 [1.18]

Crashes back to launcher before opening minecraft window

### Version

Other (this list is not up to date - again...)

### Version

forge 1.18 38.0.14 v2.1.3

### To Reproduce

Armorpoints ++ only mod in the mods folder.
Launch MC from launcher.
Wait a few seconds.
Crash.

### Relevant Log / Crash-Report Output

```shell
12:19:39.335
launcher
main
Preparing to launch minecraft client for 1.18-forge-38.0.14
12:19:40.479
launcher
main
Minecraft client 1.18-forge-38.0.14 is ready to start.
12:19:40.479
launcher
main
Starting!
12:19:41.061
launcher
main
Version does not support log configuration, will assume one plaintext entry per line
12:19:43.008
game
2021-12-06 12:19:42,994 main WARN Advanced terminal features are not available in this environment
12:19:43.178
game
[12:19:43] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Baggytrousers27, --version, 1.18-forge-38.0.14, --gameDir, G:\Mods\1.18\Forge\Installations\Testing, --assetsDir, C:\Users\Van\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, c8de556cf3a54dbcb48d4ab5b4f6acfd, --accessToken, ????????, --clientId, NDk4MzdmZDAtMWU3My00MTJjLThjZjUtNTYzMTQ4MTEwYWFm, --xuid, 2533274886435280, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 38.0.14, --fml.mcVersion, 1.18, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211130.085255]
12:19:43.191
game
[12:19:43] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 17.0.1 by Microsoft
12:19:43.330
game
[12:19:43] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Van/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2318! Service=ModLauncher Env=CLIENT
12:19:44.826
game
Exception in thread "main" java.lang.IllegalArgumentException: forge-1.18-2.1.3: Version string does not start with a number
12:19:44.826
game
at java.base/java.lang.module.ModuleDescriptor$Version.<init>(ModuleDescriptor.java:1005)
12:19:44.826
game
at java.base/java.lang.module.ModuleDescriptor$Version.parse(ModuleDescriptor.java:1090)
12:19:44.826
game
at java.base/java.lang.module.ModuleDescriptor$Builder.version(ModuleDescriptor.java:2062)
```

**Comment by Cheos137** [comment]
fixed

**Comment by Baggytrousers27** [comment]
Cheers.
