### ISSUE TITLE
[Bug]: Crash on alt+tab

### ISSUE THREAD

**Issue by frikinjay** [Cheos137/ArmorpointsPlusplus#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using the pack https://modrinth.com/modpack/packzero when alt+tab is pressed the game crashes.

### Version

3.0.1 for Minecraft Fabric 1.18.2

### To Reproduce

Install the pack, join a server then alt+tab.

### Expexted Behavior

To not crash

### Relevant Log / Crash-Report Output

```shell
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_4587 cannot be cast to class java.lang.Integer (net.minecraft.class_4587 is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @59d4cd39; java.lang.Integer is in module java.base of loader 'bootstrap')
	at net.minecraft.class_329.args$ddb000$modifyDrawTextureArgs(class_329.java:9023)
	at net.minecraft.class_329.method_1736(class_329.java:457)
	at net.minecraft.class_329.method_1753(class_329.java:235)
	at dev.cheos.armorpointspp.ApppGui.method_1753(ApppGui.java:32)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_329.args$ddb000$modifyDrawTextureArgs(class_329.java:9023)
	at net.minecraft.class_329.method_1736(class_329.java:457)
	at net.minecraft.class_329.method_1753(class_329.java:235)
	at dev.cheos.armorpointspp.ApppGui.method_1753(ApppGui.java:32)

-- Affected level --
Details:
	All players: 1 total; [class_746['Mr_Lego'/5687, l='ClientLevel', x=757.56, y=68.00, z=692.47]]
	Chunk stats: 16384, 2154
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,66,0), Section: (at 0,2,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 943847 game time, 953997 day time
	Server brand: quilt
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, charmonium/journeyman, visualoverhaul/coloredwaterbucket, visualoverhaul/fancyfurnace, visualoverhaul/nobrewingbottles, visualoverhaul/rounddiscs, 01Better_end_portal_frame, 02Canvas_Mod_Compatibility, 03More_canvas_compat, 04CTM_Overhaul, 05CTM_Overhaul_extras, 06Rail_fix, 07Soft_weather, 0shaders.zip, 13VanillaTweaks_r319626.zip, 1spatialharvesters_overhaul_16x16.zip, BuildingWands-2.1.2-fabric.zip, bfb_infchest_tweaks.zip, bfb_resourcepack.zip, bfb_valleycraft_tweaks.zip, customcursor.zip, KubeJS Resource Pack [assets]
```

**Comment by Cheos137** [comment]
can't reproduce this in either my fabric test environment or a normal fabric client.
this might be an incompatibility caused by any mod (which i don't know) or by quilt.

- anyways... i'm intrigued, so i'm going to look into this (though maybe nothing will change)

**Comment by Cheos137** [comment]
I think, even though appp shows up in the stacktrace (because it completely replaces vanillas gui instance) it's not appps fault.
I cannot point my finger at what the actual cause is, tho
