### ISSUE TITLE
[Bug]: Wear armor game crash

### ISSUE THREAD

**Issue by al-wei** [Cheos137/ArmorpointsPlusplus#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Description

Wear armor game crash

### Version

3.1.x for Minecraft Forge 1.12.2

### Version

armorpointspp-forge-1.12.2-3.1.0

### Relevant Log / Crash-Report Output

```shell
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 9/30/23 10:34 AM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.entity.ai.attributes.RangedAttribute.field_111118_b from class dev.cheos.armorpointspp.impl.DataProviderImpl
	at dev.cheos.armorpointspp.impl.DataProviderImpl.maxArmor(DataProviderImpl.java:34)
	at dev.cheos.armorpointspp.core.render.ArmorComponent.render(ArmorComponent.java:19)
	at dev.cheos.armorpointspp.Overlays.armorLevel(Overlays.java:48)
	at dev.cheos.armorpointspp.RenderGameOverlayListener.handle(RenderGameOverlayListener.java:68)
	at dev.cheos.armorpointspp.RenderGameOverlayListener.handlen(RenderGameOverlayListener.java:30)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_RenderGameOverlayListener_handlen_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.renderArmor(GuiIngameForge.java:290)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:155)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at dev.cheos.armorpointspp.impl.DataProviderImpl.maxArmor(DataProviderImpl.java:34)
	at dev.cheos.armorpointspp.core.render.ArmorComponent.render(ArmorComponent.java:19)
	at dev.cheos.armorpointspp.Overlays.armorLevel(Overlays.java:48)
	at dev.cheos.armorpointspp.RenderGameOverlayListener.handle(RenderGameOverlayListener.java:68)
	at dev.cheos.armorpointspp.RenderGameOverlayListener.handlen(RenderGameOverlayListener.java:30)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_RenderGameOverlayListener_handlen_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.renderArmor(GuiIngameForge.java:290)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:155)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['fanrenlaya'/1817, l='MpServer', x=3.10, y=64.00, z=255.38]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-4,64,252), Chunk: (at 12,4,12 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 428 game time, 428 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 62 total; [EntityPig['猪'/19, l='MpServer', x=-60.50, y=63.00, z=240.50], EntityPig['猪'/20, l='MpServer', x=-58.50, y=63.00, z=243.50], EntityPig['猪'/21, l='MpServer', x=-59.50, y=63.00, z=242.50], EntityPig['猪'/22, l='MpServer', x=-12.71, y=64.00, z=246.25], EntityPig['猪'/23, l='MpServer', x=-20.27, y=66.00, z=232.86], EntityPig['猪'/24, l='MpServer', x=-22.45, y=66.00, z=241.21], EntityPig['猪'/25, l='MpServer', x=-27.33, y=67.00, z=240.50], EntityPig['猪'/26, l='MpServer', x=0.50, y=63.00, z=311.50], EntityPig['猪'/27, l='MpServer', x=-1.50, y=63.00, z=310.50], EntityPig['猪'/28, l='MpServer', x=0.50, y=63.00, z=309.50], EntityPig['猪'/29, l='MpServer', x=-1.50, y=63.00, z=311.50], EntityBat['蝙蝠'/2689, l='MpServer', x=62.76, y=27.03, z=313.86], EntitySpider['蜘蛛'/2704, l='MpServer', x=-6.50, y=17.00, z=323.50], EntityBat['蝙蝠'/2715, l='MpServer', x=24.86, y=20.90, z=197.85], EntitySkeleton['骷髅'/2722, l='MpServer', x=-9.50, y=15.00, z=209.50], EntityBat['蝙蝠'/2723, l='MpServer', x=38.00, y=26.05, z=306.26], EntityCreeper['爬行者'/2727, l='MpServer', x=-21.50, y=52.00, z=317.50], EntityBat['蝙蝠'/2731, l='MpServer', x=-64.51, y=30.71, z=294.29], EntityCreeper['爬行者'/2733, l='MpServer', x=-4.50, y=40.00, z=185.50], EntityBat['蝙蝠'/2735, l='MpServer', x=48.19, y=28.83, z=330.61], EntityBat['蝙蝠'/2736, l='MpServer', x=-2.09, y=41.06, z=187.39], EntityZombie['僵尸'/2740, l='MpServer', x=-24.50, y=23.00, z=209.50], EntityBat['蝙蝠'/2742, l='MpServer', x=-71.25, y=33.10, z=295.45], EntityBat['蝙蝠'/2745, l='MpServer', x=-76.44, y=33.65, z=297.59], EntityItem['item.item.porkchopRaw'/2756, l='MpServer', x=-58.63, y=34.00, z=246.37], EntityZombie['僵尸'/2774, l='MpServer', x=23.49, y=20.00, z=197.25], EntityCreeper['爬行者'/2776, l='MpServer', x=81.50, y=21.00, z=285.50], EntityZombieVillager['僵尸村民'/2796, l='MpServer', x=68.53, y=26.00, z=303.30], EntityZombie['僵尸'/2805, l='MpServer', x=-66.50, y=30.00, z=292.50], EntityZombieVillager['僵尸村民'/2806, l='MpServer', x=-66.50, y=30.00, z=293.50], EntityZombieVillager['僵尸村民'/2807, l='MpServer', x=-67.50, y=30.00, z=293.50], EntityZombie['僵尸'/2814, l='MpServer', x=9.50, y=21.00, z=174.50], EntityCreeper['爬行者'/2816, l='MpServer', x=17.17, y=21.00, z=177.49], EntityZombie['僵尸'/2834, l='MpServer', x=7.50, y=44.00, z=195.50], EntitySkeleton['骷髅'/2835, l='MpServer', x=2.50, y=44.00, z=195.50], EntityCreeper['爬行者'/2852, l='MpServer', x=-11.30, y=20.18, z=214.30], EntityCreeper['爬行者'/2853, l='MpServer', x=-10.63, y=21.00, z=214.30], EntityZombie['僵尸'/2857, l='MpServer', x=-35.56, y=22.00, z=213.74], EntitySquid['鱿鱼'/1848, l='MpServer', x=-58.99, y=55.78, z=314.99], EntityWitch['女巫'/2897, l='MpServer', x=22.50, y=23.00, z=300.50], EntityBat['蝙蝠'/1877, l='MpServer', x=-34.63, y=38.47, z=189.69], EntityCreeper['爬行者'/2912, l='MpServer', x=-49.50, y=25.00, z=329.50], EntityCreeper['爬行者'/2913, l='MpServer', x=-48.41, y=25.00, z=328.80], EntityBat['蝙蝠'/1894, l='MpServer', x=-8.29, y=35.71, z=321.29], EntityCreeper['爬行者'/2919, l='MpServer', x=-67.50, y=21.00, z=231.50], EntityBat['蝙蝠'/1896, l='MpServer', x=5.44, y=27.03, z=312.92], EntityBat['蝙蝠'/1900, l='MpServer', x=-62.49, y=15.05, z=302.32], EntityBat['蝙蝠'/1902, l='MpServer', x=-54.41, y=42.43, z=260.32], EntitySkeleton['骷髅'/2937, l='MpServer', x=35.50, y=28.00, z=293.50], EntitySkeleton['骷髅'/2940, l='MpServer', x=-55.50, y=41.00, z=280.50], EntitySkeleton['骷髅'/2941, l='MpServer', x=-55.50, y=41.00, z=279.50], EntitySkeleton['骷髅'/1919, l='MpServer', x=16.50, y=26.00, z=231.50], EntityCreeper['爬行者'/2946, l='MpServer', x=-23.50, y=29.00, z=213.50], EntityCreeper['爬行者'/2947, l='MpServer', x=-23.50, y=29.00, z=214.50], EntitySkeleton['骷髅'/2952, l='MpServer', x=-19.50, y=28.00, z=214.50], EntityZombie['僵尸'/2955, l='MpServer', x=-20.52, y=11.00, z=272.75], EntitySkeleton['骷髅'/2956, l='MpServer', x=-33.50, y=31.00, z=232.50], EntityPlayerSP['fanrenlaya'/1817, l='MpServer', x=3.10, y=64.00, z=255.38], EntityEnderman['末影人'/2970, l='MpServer', x=-8.72, y=18.00, z=188.45], EntityCreeper['爬行者'/2998, l='MpServer', x=-27.50, y=31.00, z=242.50], EntityCreeper['爬行者'/2999, l='MpServer', x=-31.50, y=31.00, z=242.50], EntityCreeper['爬行者'/3021, l='MpServer', x=-51.50, y=27.00, z=200.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_381, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 579022824 bytes (552 MB) / 2013265920 bytes (1920 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 11 total; -Xmx4096m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                               | Signature                                |
	|:------ |:------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft     | 1.12.2       | minecraft.jar                        | None                                     |
	| LCHIJA | mcp           | 9.42         | minecraft.jar                        | None                                     |
	| LCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge         | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | armorpointspp | 3.1.0        | armorpointspp-forge-1.12.2-3.1.0.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 537.42' Renderer: 'NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
	Launched Version: ALY
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.42, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
```

**Comment by Cheos137** [comment]
This build should fix your issue, can you please confirm it working?

(unzip this, github doesn't let me upload `.jar` files): [armorpointspp-forge-1.12.2-3.1.3-test.jar.zip](https://github.com/Cheos137/ArmorpointsPlusplus/files/12774230/armorpointspp-forge-1.12.2-3.1.3-test.jar.zip)

**Comment by al-wei** [comment]
> This build should fix your issue, can you please confirm it working?
> 
> (unzip this, github doesn't let me upload `.jar` files): [armorpointspp-forge-1.12.2-3.1.3-test.jar.zip](https://github.com/Cheos137/ArmorpointsPlusplus/files/12774230/armorpointspp-forge-1.12.2-3.1.3-test.jar.zip)

no

**Comment by al-wei** [comment]
Is there any progress?

**Comment by Cheos137** [comment]
sorry, can't give an ETA right now.. am currently really busy

**Comment by Cheos137** [comment]
does this build work?
(again, unzip): [armorpointspp-forge-1.12.2-3.1.3-test2.jar.zip](https://github.com/Cheos137/ArmorpointsPlusplus/files/12907080/armorpointspp-forge-1.12.2-3.1.3-test2.jar.zip)

**Comment by al-wei** [comment]
> does this build work? (again, unzip): [armorpointspp-forge-1.12.2-3.1.3-test2.jar.zip](https://github.com/Cheos137/ArmorpointsPlusplus/files/12907080/armorpointspp-forge-1.12.2-3.1.3-test2.jar.zip)
Thank you for your efforts to make MC better.
![image](https://github.com/Cheos137/ArmorpointsPlusplus/assets/145486869/6b49ca1e-c50e-43ff-b5c6-471326d5b796)
